#cloud-config
users:
  - name: ${user}
    groups: users, admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ${pubkey}

package_update: true
package_upgrade: true
packages:
# basics
   - python3
  #  - git
  #  - fail2ban
  #  - tmux
  #  - telnet
  #  - vim
  #  - tcpdump
  #  - net-tools
  #  - unzip
  #  - mlocate
  #  - wget
  #  - vim
  #  - cifs-utils
  #  - screen
  #  - htop
  #  - tree
  #  - wget
# CentOS only
#  - yum-utils
#  - setroubleshoot
#  - sudo
#  - policycoreutils
#  - policycoreutils-python-utils
#  - setools
#  - setools-console
#  - setroubleshoot

runcmd:
 # - printf "[sshd]\nenabled = true\nbanaction = iptables-multiport" > /etc/fail2ban/jail.local
 # - systemctl enable fail2ban
  - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - sed -i -e '/^PasswordAuthentication/s/^.*$/PasswordAuthentication no/' /etc/ssh/sshd_config
  - sed -i -e '/^X11Forwarding/s/^.*$/X11Forwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^#MaxAuthTries/s/^.*$/MaxAuthTries 2/' /etc/ssh/sshd_config
  - sed -i -e '/^#AllowTcpForwarding/s/^.*$/AllowTcpForwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^#AllowAgentForwarding/s/^.*$/AllowAgentForwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^#AuthorizedKeysFile/s/^.*$/AuthorizedKeysFile .ssh\/authorized_keys/' /etc/ssh/sshd_config
  - sed -i '$a AllowUsers ${user}' /etc/ssh/sshd_config
  - reboot