---
- hosts: localhost
  gather_facts: false
  connection: local

  tasks:

    - name: Git checkout
      ansible.builtin.git:
        repo: 'https://github.com/kubernetes-sigs/kubespray.git'
        dest: ../kubespray
        version: v2.16.0
      tags: present

    - name: Git checkout
      file:
        path: ../kubespray
        state: absent
      tags: absent

