---
- name: namespace fip-controller
  kubernetes.core.k8s:
    name: fip-controller
    api_version: v1
    kind: Namespace
    state: present

- name: Download fip deployment yaml
  get_url:
    url: https://raw.githubusercontent.com/cbeneke/hcloud-fip-controller/master/deploy/deployment.yaml
    dest: ../values/fip/fip_deploy.yml

- name: Create a fip-controller deployment using values files
  kubernetes.core.k8s:
    state: present
    src: ../values/fip/fip_deploy.yml

- name: Download file with custom HTTP headers
  get_url:
    url: https://raw.githubusercontent.com/cbeneke/hcloud-fip-controller/master/deploy/rbac.yaml
    dest: ../values/fip/fip_rbac.yml

- name: Create a fip-controller RBAC using values files
  kubernetes.core.k8s:
    state: present
    src: ../values/fip/fip_rbac.yml

- name: Create a fip-controller using template
  kubernetes.core.k8s:
    state: present
    template: ../templates/fip/fip-controller.j2
